# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Opinion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Opinion

pod 'ConfettiView-NSHipster'

  target 'OpinionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpinionUITests' do
    # Pods for testing
  end

end
